development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://dlsjehcayujqmf:2a4e4a6963d593d689a39d02012166a48ce312fd6ae8ffec2bb4e2e40d68e70a@ec2-54-225-70-53.compute-1.amazonaws.com:5432/dd2iaosvljv72s
  channel_prefix: app_production
